pos_dittos = {
        'JJ': ['JJ',
            'JJ21',
            'JJ22',
            'JJ31',
            'JJ32',
            'JJ33'],
        'JJR': ['JJR'],
        'JJT': ['JJT'],
        'JK': ['JK'],
        'RA': ['RA',
            'RA21',
            'RA22'],
        'REX': ['REX',
            'REX21',
            'REX22',
            'REX41',
            'REX42',
            'REX43',
            'REX44'],
        'RG': ['RG',
            'RG21',
            'RG22'],
        'RGQ': ['RGQ'],
        'RGQV': ['RGQV',
            'RGQV31',
            'RGQV32',
            'RGQV33'],
        'RGR': ['RGR'],
        'RGT': ['RGT'],
        'RL': ['RL',
            'RL21',
            'RL22'],
        'RP': ['RP'],
        'RPK': ['RPK'],
        'RR': ['RR',
            'RR21',
            'RR22',
            'RR31',
            'RR32',
            'RR33',
            'RR41',
            'RR42',
            'RR43',
            'RR44'],
        'RRQ': ['RRQ'],
        'RRQV': ['RRQ'],
        'RRR': ['RRR'],
        'RRT': ['RRT'],
        'RT': ['RT',
            'RT21',
            'RT22',
            'RT41',
            'RT42',
            'RT43',
            'RT44'],
        'CC': ['CC'],
        'CCB': ['CCB'],
        'CS': ['CS',
            'CS21',
            'CS22',
            'CS31',
            'CS32',
            'CS33',
            'CS41',
            'CS42',
            'CS43',
            'CS44'],
        'CSA': ['CSA'],
        'CSN': ['CSN'],
        'CST': ['CST'],
        'CSW': ['CSW',
            'CSW31',
            'CSW32',
            'CSW33'],
        'DA': ['DA'],
        'DA1': ['DA1'],
        'DA2': ['DA2'],
        'DAR': ['DAR'],
        'DAT': ['DAT'],
        'DB': ['DB'],
        'DB2': ['DB2'],
        'DD': ['DD'],
        'DD1': ['DD1'],
        'DD2': ['DD2'],
        'DDQ': ['DDQ'],
        'DDQGE': ['DDQGE'],
        'DDQV': ['DDQV', 
            'DDQV31',
            'DDQV32',
            'DDQV33'],
        'ND1': ['ND1'],
        'NN': ['NN'],
        'NN1': ['NN1',
            'NN121',
            'NN122',
            'NN131',
            'NN132',
            'NN133'],
        'NN2': ['NN2'],
        'NNA': ['NNA'],
        'NNB': ['NNB'],
        'NNL1': ['NNL1'],
        'NNL2': ['NNL2'],
        'NNO': ['NNO'],
        'NNO2': ['NNO2'],
        'NNT1': ['NNT1'],
        'NNT2': ['NNT2'],
        'NNU': ['NNU'],
        'NNU1': ['NNU1'],
        'NNU2': ['NNU2',
            'NNU21',
            'NNU22'],
        'NP': ['NP'],
        'NP1': ['NP1'],
        'NP2': ['NP2'],
        'NPD1': ['NPD1'],
        'NPD2': ['NPD2'],
        'NPM1': ['NPM1'],
        'MC': ['MC'],
        'MC1': ['MC1'],
        'MC2': ['MC2'],
        'MCMC': ['MCMC'],
        'MD': ['MD'],
        'MF': ['MF'],
        'IF': ['IF'],
        'II': ['II',
            'II21',
            'II22',
            'II31',
            'II32',
            'II33',
            'II41',
            'II42',
            'II43',
            'II44'],
        'IO': ['IO'],
        'IW': ['IW'],
        'PN': ['PN'],
        'PN1': ['PN1',
            'PN121',
            'PN122',
            'PN21',
            'PN22'],
        'PNQO': ['PNQO'],
        'PNQS': ['PNQS'],
        'PNQV': ['PNQV'],
        'PNX1': ['PNX1'],
        'PPGE': ['PPGE'],
        'PPH1': ['PPH1'],
        'PPHO1': ['PPHO1'],
        'PPHO2': ['PPHO2'],
        'PPHS1': ['PPHS1'],
        'PPHS2': ['PPHS2'],
        'PPIO1': ['PPIO1'],
        'PPIO2': ['PPIO2'],
        'PPIS1': ['PPIS1'],
        'PPIS2': ['PPIS2'],
        'PPX1': ['PPX1',
            'PPX121',
            'PPX122'],
        'PPX2': ['PPX2',
            'PPX221',
            'PPX222'],
        'PPY': ['PPY'],
        'VB0': ['VB0'],
        'VBDR': ['VBDR'],
        'VBDZ': ['VBDZ'],
        'VBG': ['VBG'],
        'VBI': ['VBI'],
        'VBM': ['VBM'],
        'VBN': ['VBN'],
        'VBR': ['VBR'],
        'VBZ': ['VBZ'],
        'VD0': ['VD0'],
        'VDD': ['VDD'],
        'VDG': ['VDG'],
        'VDI': ['VDI'],
        'VDN': ['VDN'],
        'VDZ': ['VDZ'],
        'VH0': ['VH0'],
        'VHD': ['VHD'],
        'VHG': ['VHG'],
        'VHI': ['VHI'],
        'VHN': ['VHN'],
        'VHZ': ['VHZ'],
        'VM': ['VM',
            'VM21',
            'VM22'],
        'VMK': ['VMK'],
        'VV0': ['VV0'],
        'VVD': ['VVD'],
        'VVG': ['VVG'],
        'VVGK': ['VVGK'],
        'VVI': ['VVI'],
        'VVN': ['VVN'],
        'VVNK': ['VVNK'],
        'VVZ': ['VVZ'],
        'APPGE': ['APPGE'],
        'AT': ['AT'],
        'AT1': ['AT1'],
        'BCL': ['BCL', 
            'BCL21', 
            'BCL22'],
        'EX': ['EX'],
        'FO': ['FO'],
        'FU': ['FU'],
        'FW': ['FW'],
        'GE': ['GE'],
        'TO': ['TO'],
        'UH': ['UH'],
        'XX': ['XX'],
        'ZZ1': ['ZZ1'],
        'ZZ2': ['ZZ2',
            'ZZ221',
            'ZZ222']
}

pos_labels = {
        'JJ':'general adjective',
        'JJR':'general comparative adjective (e.g. older, better, stronger)',
        'JJT':'general superlative adjective (e.g. oldest, best, strongest)',
        'JK':'catenative adjective (able in be able to, willing in be willing to)',
        'RA':'adverb, after nominal head (e.g. else, galore)',
        'REX':'adverb introducing appositional constructions (namely, e.g.)',
        'RG':'degree adverb (very, so, too)',
        'RGQ':'wh- degree adverb (how)',
        'RGQV':'wh-ever degree adverb (however)',
        'RGR':'comparative degree adverb (more, less)',
        'RGT':'superlative degree adverb (most, least)',
        'RL':'locative adverb (e.g. alongside, forward)',
        'RP':'prep. adverb, particle (e.g about, in)',
        'RPK':'prep. adv., catenative (about in be about to)',
        'RR':'general adverb',
        'RRQ':'wh- general adverb (where, when, why, how)',
        'RRQV':'wh-ever general adverb (wherever, whenever)',
        'RRR':'comparative general adverb (e.g. better, longer)',
        'RRT':'superlative general adverb (e.g. best, longest)',
        'RT':'quasi-nominal adverb of time (e.g. now, tomorrow)',
        'CC':'coordinating conjunction (e.g. and, or)',
        'CCB':'adversative coordinating conjunction ( but)',
        'CS':'subordinating conjunction (e.g. if, because, unless, so, for)',
        'CSA':'as (as conjunction)',
        'CSN':'than (as conjunction)',
        'CST':'that (as conjunction)',
        'CSW':'whether (as conjunction)',
        'DA':'after-determiner or post-determiner capable of pronominal function (e.g. such, former, same)',
        'DA1':'singular after-determiner (e.g. little, much)',
        'DA2':'plural after-determiner (e.g. few, several, many)',
        'DAR':'comparative after-determiner (e.g. more, less, fewer)',
        'DAT':'superlative after-determiner (e.g. most, least, fewest)',
        'DB':'before determiner or pre-determiner capable of pronominal function (all, half)',
        'DB2':'plural before-determiner ( both)',
        'DD':'determiner (capable of pronominal function) (e.g any, some)',
        'DD1':'singular determiner (e.g. this, that, another)',
        'DD2':'plural determiner ( these,those)',
        'DDQ':'wh-determiner (which, what)',
        'DDQGE':'wh-determiner, genitive (whose)',
        'DDQV':'wh-ever determiner, (whichever, whatever)',
        'ND1':'singular noun of direction (e.g. north, southeast)',
        'NN':'common noun, neutral for number (e.g. sheep, cod, headquarters)',
        'NN1':'singular common noun (e.g. book, girl)',
        'NN2':'plural common noun (e.g. books, girls)',
        'NNA':'following noun of title (e.g. M.A.)',
        'NNB':'preceding noun of title (e.g. Mr., Prof.)',
        'NNL1':'singular locative noun (e.g. Island, Street)',
        'NNL2':'plural locative noun (e.g. Islands, Streets)',
        'NNO':'numeral noun, neutral for number (e.g. dozen, hundred)',
        'NNO2':'numeral noun, plural (e.g. hundreds, thousands)',
        'NNT1':'temporal noun, singular (e.g. day, week, year)',
        'NNT2':'temporal noun, plural (e.g. days, weeks, years)',
        'NNU':'unit of measurement, neutral for number (e.g. in, cc)',
        'NNU1':'singular unit of measurement (e.g. inch, centimetre)',
        'NNU2':'plural unit of measurement (e.g. ins., feet)',
        'NP':'proper noun, neutral for number (e.g. IBM, Andes)',
        'NP1':'singular proper noun (e.g. London, Jane, Frederick)',
        'NP2':'plural proper noun (e.g. Browns, Reagans, Koreas)',
        'NPD1':'singular weekday noun (e.g. Sunday)',
        'NPD2':'plural weekday noun (e.g. Sundays)',
        'NPM1':'singular month noun (e.g. October)',
        'MC':'cardinal number,neutral for number (two, three..)',
        'MC1':'singular cardinal number (one)',
        'MC2':'plural cardinal number (e.g. sixes, sevens)',
        'MCMC':'hyphenated number (40-50, 1770-1827)',
        'MD':'ordinal number (e.g. first, second, next, last)',
        'MF':'fraction,neutral for number (e.g. quarters, two-thirds)',
        'IF':'for (as preposition)',
        'II':'general preposition',
        'IO':'of (as preposition)',
        'IW':'with, without (as prepositions)',
        'PN':'indefinite pronoun, neutral for number (none)',
        'PN1':'indefinite pronoun, singular (e.g. anyone, everything, nobody, one)',
        'PNQO':'objective wh-pronoun (whom)',
        'PNQS':'subjective wh-pronoun (who)',
        'PNQV':'wh-ever pronoun (whoever)',
        'PNX1':'reflexive indefinite pronoun (oneself)',
        'PPGE':'nominal possessive personal pronoun (e.g. mine, yours)',
        'PPH1':'3rd person sing. neuter personal pronoun (it)',
        'PPHO1':'3rd person sing. objective personal pronoun (him, her)',
        'PPHO2':'3rd person plural objective personal pronoun (them)',
        'PPHS1':'3rd person sing. subjective personal pronoun (he, she)',
        'PPHS2':'3rd person plural subjective personal pronoun (they)',
        'PPIO1':'1st person sing. objective personal pronoun (me)',
        'PPIO2':'1st person plural objective personal pronoun (us)',
        'PPIS1':'1st person sing. subjective personal pronoun (I)',
        'PPIS2':'1st person plural subjective personal pronoun (we)',
        'PPX1':'singular reflexive personal pronoun (e.g. yourself, itself)',
        'PPX2':'plural reflexive personal pronoun (e.g. yourselves, themselves)',
        'PPY':'2nd person personal pronoun (you)',
        'VB0':'be, base form (finite i.e. imperative, subjunctive)',
        'VBDR':'were',
        'VBDZ':'was',
        'VBG':'being',
        'VBI':'be, infinitive (To be or not... It will be ..)',
        'VBM':'am',
        'VBN':'been',
        'VBR':'are',
        'VBZ':'is',
        'VD0':'do, base form (finite)',
        'VDD':'did',
        'VDG':'doing',
        'VDI':'do, infinitive (I may do... To do...)',
        'VDN':'done',
        'VDZ':'does',
        'VH0':'have, base form (finite)',
        'VHD':'had (past tense)',
        'VHG':'having',
        'VHI':'have, infinitive',
        'VHN':'had (past participle)',
        'VHZ':'has',
        'VM':'modal auxiliary (can, will, would, etc.)',
        'VMK':'modal catenative (ought, used)',
        'VV0':'base form of lexical verb (e.g. give, work)',
        'VVD':'past tense of lexical verb (e.g. gave, worked)',
        'VVG':'-ing participle of lexical verb (e.g. giving, working)',
        'VVGK':'-ing participle catenative (going in be going to)',
        'VVI':'infinitive (e.g. to give... It will work...)',
        'VVN':'past participle of lexical verb (e.g. given, worked)',
        'VVNK':'past participle catenative (e.g. bound in be bound to)',
        'VVZ':'-s form of lexical verb (e.g. gives, works)',
        'APPGE':'possessive pronoun, pre-nominal (e.g. my, your, our)',
        'AT':'article (e.g. the, no)',
        'AT1':'singular article (e.g. a, an, every)',
        'BCL':'before-clause marker (e.g. in order (that),in order (to))',
        'EX':'existential there',
        'FO':'formula',
        'FU':'unclassified word',
        'FW':'foreign word',
        'GE':'germanic genitive marker - (\' or\'s)',
        'TO':'infinitive marker (to)',
        'UH':'interjection (e.g. oh, yes, um)',
        'XX':'not, n\'t',
        'ZZ1':'singular letter of the alphabet (e.g. A,b)',
        'ZZ2':'plural letter of the alphabet (e.g. A\'s, b\'s)'
}

pos_categories = {
    'adjectives': [
        'JJ',
        'JJR',
        'JJT',
        'JK',
    ],
    'adverbs': [
        'RA',
        'REX',
        'RG',
        'RGQ',
        'RGQV',
        'RGR',
        'RGT',
        'RL',
        'RP',
        'RPK',
        'RR',
        'RRQ',
        'RRQV',
        'RRR',
        'RRT',
        'RT',
    ],
    'conjunctions': [
        'CC',
        'CCB',
        'CS',
        'CSA',
        'CSN',
        'CST',
        'CSW',
    ],
    'determiners': [
        'DA',
        'DA1',
        'DA2',
        'DAR',
        'DAT',
        'DB',
        'DB2',
        'DD',
        'DD1',
        'DD2',
        'DDQ',
        'DDQGE',
        'DDQV', 
    ],
    'nouns': [
        'ND1',
        'NN',
        'NN1',
        'NN2',
        'NNA',
        'NNB',
        'NNL1',
        'NNL2',
        'NNO',
        'NNO2',
        'NNT1',
        'NNT2',
        'NNU',
        'NNU1',
        'NNU2',
        'NP',
        'NP1',
        'NP2',
        'NPD1',
        'NPD2',
        'NPM1',
    ],
    'numerics': [
        'MC',
        'MC1',
        'MC2',
        'MCMC',
        'MD',
        'MF',
    ],
    'prepositions': [
        'IF',
        'II',
        'IO',
        'IW',
    ],
    'pronouns': [
        'PN',
        'PN1',
        'PNQO',
        'PNQS',
        'PNQV',
        'PNX1',
        'PPGE',
        'PPH1',
        'PPHO1',
        'PPHO2',
        'PPHS1',
        'PPHS2',
        'PPIO1',
        'PPIO2',
        'PPIS1',
        'PPIS2',
        'PPX1',
        'PPX2',
        'PPY',
    ],
    'verbs': [
        'VB0',
        'VBDR',
        'VBDZ',
        'VBG',
        'VBI',
        'VBM',
        'VBN',
        'VBR',
        'VBZ',
        'VD0',
        'VDD',
        'VDG',
        'VDI',
        'VDN',
        'VDZ',
        'VH0',
        'VHD',
        'VHG',
        'VHI',
        'VHN',
        'VHZ',
        'VM',
        'VMK',
        'VV0',
        'VVD',
        'VVG',
        'VVGK',
        'VVI',
        'VVN',
        'VVNK',
        'VVZ',
    ],
    'not categorized': [
        'APPGE',
        'AT',
        'AT1',
        'BCL', 
        'EX',
        'FO',
        'FU',
        'FW',
        'GE',
        'TO',
        'UH',
        'XX',
        'ZZ1',
        'ZZ2',
    ]
}
